services:
  - type: web
    name: laundry-backend
    runtime: python
    buildCommand: "pip install -r requirements.txt && playwright install"
    startCommand: "gunicorn laundry_backend:app"
    envVars: []
