services:
  - type: web
    name: laundry-backend
    runtime: python
    buildCommand: "python3 -m pip install -r requirements.txt && python3 -m playwright install"
    startCommand: "gunicorn laundry_backend:app"
    envVars: []
